# Generated by Django 2.2.6 on 2019-10-08 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(default='default.png', upload_to='pics')),
                ('image1', models.ImageField(default='default.png', upload_to='pics')),
                ('image2', models.ImageField(default='default.png', upload_to='pics')),
                ('image3', models.ImageField(default='default.png', upload_to='pics')),
                ('desc', models.TextField(max_length=500)),
                ('amen', models.TextField(max_length=500)),
                ('address', models.CharField(max_length=255)),
                ('ph_no', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgs.Area')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgs.Gender')),
            ],
        ),
    ]
